[package]
name = "lamuta"
version = "0.3.2"
edition = "2021"
authors = ["梶塚太智 <kajizukataichi@outlook.jp>"]
license = "MIT"

[dependencies]
colored = "2.0"
reqwest = { version = "0.12.10", features = ["blocking"] }
